language: node_js
node_js:
  - "12.18.3"
  - lts/*

services:
  - docker

before_script:
  - npm install -g truffle@5.1.35
  - docker-compose pull
  - docker-compose up -d

after_script:
  - docker-compose down